
def books = [
'Andai, dentro la notte illuminata',
'Arancia Meccanica',
'Artemisia',
'Bartleby lo scrivano',
'Bel Ami',
'Camera con vista',
'Canne al vento',
"Casa d'altri",
'Cattedrale',
'Cattivo Natale',
'Cenere',
"Chissà dov'ero quel 25 aprile",
'Ciàula scopre la luna',
'Collettori - Limonata',
'Con gli occhi chiusi',
'Conservazione',
'Cristo si è fermato a Eboli',
'Cuore di cane',
'Cuore di tenebra',
'Da Quarto al Volturno',
'Decamerone',
"Di' alle donne che usciamo",
'Diario 1941-1943 di Etty Hillesum',
'Diario di Anna Frank',
'Diario di un pazzo',
'Dieci indiani e Campo indiano',
'Distanza',
'Doppio sogno',
'Dracula',
'Emma',
'Fame',
'Febbre',
'Fiabe dei fratelli Grimm',
'Flush. Una biografia',
'Fosca',
'Frankenstein',
'Gioventù senza Dio',
'Giro di Vite',
'Gli indifferenti',
"Gli occhiali d'oro",
'Gli ultimi anni di Clelia Trotti',
'Grande fiume dai due cuori',
'Grandi speranze',
'Grisha e il racconto del giardiniere capo',
"Ho servito il re d'Inghilterra",
'I Malavoglia',
'I dieci giorni che sconvolsero il mondo',
'I dolori del giovane Werther',
'I miei premi',
'I mille da Genova a Capua',
'I padri lontani',
'I promessi sposi',
'I racconti di Alberto Moravia',
'I racconti di Anton Cechov',
'I racconti di Ernest Hemingway',
'I racconti di Franz Kafka',
'I racconti di Grace Paley',
'I racconti di Italo Calvino',
'I racconti di Jack London',
'I racconti di Katherine Mansfield',
'I racconti di Lev Tolstoj',
'I racconti di Luigi Pirandello',
'I racconti di Raymond Carver',
'I racconti di Ryunosuke Akutagawa',
'I ragazzi della Via Pal',
'I tre moschettieri',
'I vecchi e i giovani',
'I viaggi di Gulliver',
'Il Conte di Montecristo',
'Il Milione',
'Il cappello del prete',
'Il commesso',
'Il compagno',
'Il comunista',
'Il conformista',
'Il deserto della Libia',
'Il diavolo in corpo',
'Il diavolo sulle colline',
'Il disperso',
'Il fondo della bottiglia',
'Il fu Mattia Pascal',
'Il giardino dei Finzi Contini',
'Il gioco dei regni',
'Il giornalino di Gian Burrasca',
'Il giorno del giudizio',
'Il giuoco delle perle di vetro',
'Il grande Bob',
'Il grande Gatsby',
'Il libro della giungla',
'Il maestro e Margherita',
'Il mago di Oz',
'Il mantello',
'Il mistero di Edwin Drood',
'Il monaco',
'Il naso',
'Il nome della rosa',
'Il paese di cuccagna',
'Il piacere',
'Il pranzo di Babette',
'Il ritratto',
'Il ritratto di Dorian Gray',
'Il rosso e il nero',
'Il sentiero dei nidi di ragno',
'Il sergente nella neve',
'Il sistema periodico',
'Il soccombente',
'Jakob von Gunten',
'Jane Eyre',
'Jules e Jim',
"L'Iguana",
"L'Imperatore di Portugallia",
"L'agente segreto",
"L'edera",
"L'educazione sentimentale",
"L'ora di tutti",
'La bella estate',
'La coscienza di Zeno',
"La linea d'ombra",
'La luna e i falò',
'La metamorfosi',
'La morte di Ivan Ilich',
'La parete',
'La paura',
'La pelle',
'La peste',
'La ricorrenza',
'La ricreazione è finita',
'La scoperta del Bambino',
'La signora Dalloway',
'La tregua',
'La vergine nel giardino',
'Lazarillo de Tormes',
'Le avventure di Pinocchio',
'Le avventure di Tom Sawyer',
"Le linee d'ombra",
'Le memorie di Barry Lindon',
'Le meraviglie del Duemila',
'Le terre del Sacramento',
'Le tigri di Mompracem',
'Le voci della sera',
'Le voci di Marrakech',
'Libera la Karenina che è in te',
'Lida Mantovani',
'Lo stadio di Wimbledon',
'Ma gli androidi sognano pecore elettriche?',
'Madame Bovary',
'Martin Eden',
'Memorie del sottosuolo',
'Mephisto',
'Metello',
"Nemici, una storia d'amore",
'Niente di nuovo sul fronte occidentale',
'Oblomov',
'Ognuno muore solo',
'Orgoglio e Pregiudizio',
'Otto ebrei',
'Padri e figli',
'Panchine. Come uscire dal mondo senza uscirne',
'Panorama',
'Passaggio in India',
'Penny Wirton e sua madre',
'Peter Pan',
'Prospettiva Nevskij',
'Racconti romani',
'Ragazzi di vita',
'Resurrezione',
'Revolutionary road',
"Riflessi in un occhio d'oro",
'Ritratto di Sarah Malcolm',
'Se questo è un uomo',
'Senilità',
'Sorelle Materassi',
'Sostiene Pereira',
'Sotto il vulcano',
'Spia per scommessa',
'Tra donne sole',
'Ultimo viene il corvo',
"Un anno sull'altipiano",
'Un uomo che dorme',
'Una cosa divertente che non farò mai più',
"Una notte del '43",
'Una storia dilettevole della musica',
'Una vita violenta',
'Uno studio in rosso',
'Uno, nessuno e centomila',
'Uova fatali',
'Utz',
"Vent'anni dopo",
'Ventimila leghe sotto i mari',
'Vita di Galileo',
'Vita precaria e amore eterno', ]

books.each { book ->
    def fileName = nameToFile(book) + '.xml'
    println "$book -> $fileName"
    def file = new File(fileName)
    if (file.exists()) {
        println "File $fileName already exists."
    } else {
        file.createNewFile()
        println "File $fileName created."
    }
}

def nameToFile(String name) {
    name = name.replaceAll(/'|’/, '')
    name = name.split(/\s+/).collect { it.capitalize() }.join('')
    name
}
