name: Check "Ad Alta Voce" Podcasts

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
     - cron: "30 7 * * 0"   # Runs at 08:30 UTC on Mondays

permissions:
  contents: write  # Allows pushing changes
  
jobs:
  Update-RSS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.0.15'

      - name: Ad Alta Voce
        run: |
          groovy rss/AdAltaVoce.groovy
          echo "path"
          realpath .
          echo "find"
          find . -name "AdAltaVoce.xml"
          date > rss/AdAltaVoce.update
          git config --global user.name "giamtrot"
          git config --global user.email "giamtrot@hotmail.com"
          find rss -name "*.xml" -print -exec git add {} \;
          find . -name "AdAltaVoce.date" -print -exec git add {} \;
          find . -name "AdAltaVoce.update" -print -exec git add {} \;
          git remote -v
          git status
          git diff --cached --quiet || git commit -m "Updated AdAltaVoce.xml from GitHub Actions"
          # git push
          git status
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/giamtrot/varie.git
          
