name: Changed "Il Post" via Email

on:
  push:
    paths:
      - 'rss/IlPost.xml'  

jobs:
  debug-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Dump job context
        run: echo "${{ toJson(job) }}"

      - name: Dump runner context
        run: echo "${{ toJson(runner) }}"

      - name: Dump matrix context
        run: echo "${{ toJson(matrix) }}"

      - name: Dump all environment variables
        run: env

  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: "🚨 Changed: Il Post"
          to: raffaele.giammario@gmail.com
          from: GitHub Action <raffaele.giammario@gmail.com>
          body: ${{ github.event.head_commit.message }}
