name: Check "Il Post" Podcasts

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "*/10 6-7 * * 1-6"    # Runs every 10 minutes between 6 AM and 8 AM UTC (Daylight saving time) - Monday to Saturday
    - cron: "*/10 15-16 * * 1-5"  # Runs every 10 minutes between 15 PM and 15 PM UTC (Daylight saving time) - Monday to Friday
    

permissions:
  contents: write  # Allows pushing changes
  
jobs:
  Update-RSS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.0.15'

      - name: Il Post
        id: IlPost
        run: |
          groovy rss/IlPost.groovy
          echo "path"
          realpath .
          echo "find"
          # find . -name "IlPost.xml"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          find rss -maxdepth 1 -name "IlPost.xml" -exec git add -v {} \;
          find rss -maxdepth 1 -name "IlPost.map.json" -exec git add -v {} \;

          count=$(git status --short | wc -l)
          echo "Count: $count"

          echo "git status --short"
          git status --short

          echo "git status"
          git status 

          git diff --cached --quiet || git commit -m "Updated ilPost.xml from GitHub Actions"

          if [ "$count" -gt 0 ]; then
            echo "Changes detected, sending email..."
            echo "send_email=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes detected, not sending email."
            echo "send_email=false" >> "$GITHUB_OUTPUT"
          fi

          git push
      
      - name: Send Email Notification
        if: ${{ steps.IlPost.outputs.send_email == 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: "🚨 Changed: Il Post"
          to: raffaele.giammario@gmail.com
          from: GitHub Action <raffaele.giammario@gmail.com>
          body: ${{ github.event.head_commit.message }}
