name: Run Il Post Groovy Script

on:
  workflow_dispatch:  # Enables manual trigger

permissions:
  contents: write  # Allows pushing changes
  
jobs:
  run-groovy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v1
        with:
          groovy-version: '4.0.15'

      - name: Il Post
        run: |
          groovy rss/IlPost.groovy
          realpath .
          find . -name "ilPost.xml"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          find . -name "ilPost.xml" -print -exec git add {} \;
          git commit -m "Add ilPost.xml from GitHub Actions"
          git push
          
      #- name: Commit and Push Changes
      #  run: |
       #   
       #   
        #  
         # 
          #
          
